@local=http://localhost:3000

GET {{local}}/users/test

### Create New User
POST {{local}}/users
Content-Type: application/json

{
    "name": "daniel", 
    "email": "a@aa.com" , 
    "password": "Aa123456",
    "biz": true
}



### Authenticate (login)
POST {{local}}/auth
Content-Type: application/json

{
  "email": "a@a.com",
  "password": "Aa123456"
}