@local=http://localhost:3000


POST {{local}}/messages
Content-Type: application/json

{
    "from": "avi", 
    "to" : "shalom", 
    "message": "hello",
    "daniel says": "he is the king"
}

### 


GET {{local}}/messages
###
GET {{local}}/messages?to=
###
GET {{local}}/messages?from=

####
GET {{local}}/messages?fromDate=2023-08--16&toDate=2023-08-16


###
GET {{local}}/messages/a7a65b11-a2f7-496b-8fc3-361ee1270392

###
DELETE {{local}}/messages/a7a65b11-a2f7-496b-8fc3-361ee1270392

####
POST {{local}}/messages/clear/shalom